WIP on ghc 9.4 support
compiling-to-categories/concat pull request #113
Opened 2023-07-07 15:35 UTC by mikesperber

Fails on gold tests like so:

[3 of 4] Compiling BasicTests       ( test/BasicTests.hs, /Users/sperber/soft/siemens-anomalien/concat/dist-newstyle/build/x86_64-osx/ghc-9.4.5/concat-plugin-0.3.0.0/t/gold-tests/build/gold-tests/gold-tests-tmp/BasicTests.o )

<no location info>: error:
    panic! (the 'impossible' happened)
  GHC version 9.4.5:
	lookupIdSubst
  lvl_sbwQ
  InScope {}
  Call stack:
      CallStack (from HasCallStack):
        callStackDoc, called at compiler/GHC/Utils/Panic.hs:182:37 in ghc:GHC.Utils.Panic
        pprPanic, called at compiler/GHC/Core/Subst.hs:260:17 in ghc:GHC.Core.Subst

2023-09-18 05:12 UTC, kenranunderscore commented
I can confirm that the `concat` plugin work with GHC 9.4, based on these changes in our fork.
We are using a newer version though, 9.4.6 (and will probably be switching to 9.4.8 once/if it is released).

Don't know about the garnix and CI stuff, though. Maybe @sellout can chime in here? :)

(Also, am I imagining things, or didn't we have the 9.0 build failing before using `cabal v2-build`, but work with Nix, and now the CI seems to show the same (number of) failing tests, but for 9.2 :thinking: )

2023-09-18 05:14 UTC, kenranunderscore approved these changes

2023-09-18 13:55 UTC, sellout requested changes
It looks like the previous builds were killed for an unknown reason. I’ve restarted a couple to see how they go, but there’s at least one legit failure so far.

The GH workflow for 9.2 is also failing, but that’s due to gold tests, which I think were failing before this PR anyway?

2023-09-19 06:47 UTC, mikesperber commented on plugin/src/ConCat/Plugin.hs
> +    -- | Substitute new subexpressions for variables in an expression. Drop any dead
I've changed it, but we'll have to see: I don't see this message locally.

2023-09-19 06:47 UTC, mikesperber commented
> The GH workflow for 9.2 is also failing, but that’s due to gold tests, which I think were failing before this PR anyway?

Yes. There's some weird problem where building via Nix changes ghc's inlining strategy slightly as compared to Cabal. We'll have another look at it once this is merged.

2023-09-19 15:55 UTC, mikesperber commented on plugin/src/ConCat/Plugin.hs
> +    -- | Substitute new subexpressions for variables in an expression. Drop any dead
@sellout Haddock seems to have gone through now. OK to merge?

2023-09-19 16:09 UTC, sellout commented on plugin/src/ConCat/Plugin.hs
> +    -- | Substitute new subexpressions for variables in an expression. Drop any dead
Yep, this is now in a strictly better state than master.

master: 2 cancelled, 19 failing, and 49 successful checks
this PR: 73 successful, 1 cancelled, and 17 failing checks

(don’t know why GH is inconsistent with the ordering of successful/cancelled/failing)

I also removed the “required” flag from the GHC 9.2.4 checks that no longer exist, but didn’t add ones for 9.2.8. I figure until we have consistent passage, it’s more frustrating than helpful; and GH’s interface for changing required checks is painful (so might be worth adopting [Probot’s Settings app](https://probot.github.io/apps/settings/), which I’ve already done in some personal projects).

2023-09-19 16:09 UTC, sellout approved these changes

2023-09-19 18:17 UTC, kenranunderscore commented
Just FYI, I'm quite certain that the "5 out of 83 tests" in the gold test suite failed on a different GHC version before (9.0) and has since "moved up" to now fail on 9.2 instead. Very weird; see https://github.com/compiling-to-categories/concat/pull/111#discussion_r1122078378

2023-09-20 07:10 UTC, mikesperber commented
Moving this to master now.

2023-09-20 07:10 UTC, merged